============================= test session starts ==============================
platform linux -- Python 3.11.8, pytest-8.0.0, pluggy-1.4.0
rootdir: /home/runner/work/Assessment-Backend-Week-1/Assessment-Backend-Week-1
collected 85 items

days_api/test_api.py ................................................... [ 60%]
.........                                                                [ 70%]
days_api/test_date_functions.py .........................                [100%]

============================== 85 passed in 0.22s ==============================
************* Module app
days_api/app.py:38:11: R1729: Use a generator instead 'all(k in data for k in ['first', 'last'])' (use-a-generator)
days_api/app.py:48:4: W0702: No exception type(s) specified (bare-except)
days_api/app.py:66:4: W0702: No exception type(s) specified (bare-except)
days_api/app.py:87:8: W0702: No exception type(s) specified (bare-except)
days_api/app.py:71:0: R1710: Either all return statements in a function should return an expression, or none of them should. (inconsistent-return-statements)
************* Module date_functions
days_api/date_functions.py:13:8: W0707: Consider explicitly re-raising using 'except Exception as exc' and 'raise ValueError('Unable to convert value to datetime.') from exc' (raise-missing-from)

------------------------------------------------------------------
Your code has been rated at 9.73/10 (previous run: 9.73/10, +0.00)

